### ISSUE TITLE
Unsupported config option for services.litestream: 'profiles'

### ISSUE THREAD

**Issue by enzifiri** [ar-io/ar-io-node#130]
<h2> Hi, I was getting the attached error after I did the last update. I noticed that removing the profile section fixed this error. Could you please review it? </h2>

PR
# https://github.com/ar-io/ar-io-node/pull/127

error:
![image](https://github.com/ar-io/ar-io-node/assets/76253089/daa83bce-8eba-4d41-aaf0-07c1698cf665)

**Comment by enzifiri** [comment]
> @enzifiri Can you try upgrading `docker-compose` on your system and see if that resolves the issue?

It was fixed after I updated my version. 
Now I get this warning, but it has not caused any problems. I just wanted to let you know.

WARN[0000] /root/ar-io-node/docker-compose.yaml: `version` is obsolete

docker version:
`Docker Compose version v2.27.0`

**Comment by djwhitt** [comment]
@enzifiri Cool glad that resolved it and thanks for the heads up about the warning. We'll clean that up in the next release.

**Comment by enzifiri** [comment]
> @enzifiriSorunun çözüldüğüne çok sevindim ve uyarıyla ilgili uyarınız için teşekkürler. Bir sonraki sürümde bunu temizleyeceğiz.

Thank you, then there is no need for PR #127, you can close it.

**Comment by aantop** [comment]
![vvvvp](https://github.com/ar-io/ar-io-node/assets/136252139/17e0b62b-f135-4ca1-8e8b-3149aee16b7b)
how to fix this sir?
