### ISSUE TITLE
docs: specify and describe all envs in docs

### ISSUE THREAD

**Issue by rixcian** [ar-io/ar-io-node#47]
There's no documentation about the `envs` the gateway operator can use/edit.

The operator has to look at the `config.ts` file and find out what `envs` the gateway is trying to load from the `.env` file.

I would suggest creating the following:
- [ ] `.env.example` file, where all possible `envs` will be specified and describe what they do
- [ ] Specify and describe all `envs` in the clear table for these files:
  - [ ] README.md
  - [ ] Official docs (`linux-setup.md`, `windows-setup.md`)

The table in markdown could look like this:

| ENV_NAME     | DEFAULT_VALUE | DESCRIPTION                                    |
|--------------|---------------|------------------------------------------------|
| START_HEIGHT | 0             | Starting block height for node synchronization |
| ...          | ...           | ...                                            |

If you're okay with this proposal, could you assign it to me? I'm open to doing it.

Thanks in advance for feedback :)

**Comment by rixcian** [comment]
I think this PR can be closed now (#49 is already merged to the main branch).

**Comment by djwhitt** [comment]
@rixcian Closing. Thanks for the reminder!
