### ISSUE TITLE
PROPOSAL: Images not loading on gateway: (default) SANDBOX_PROTOCOL = "https"

### ISSUE THREAD

**Issue by twilson63** [ar-io/ar-io-node#56]
## Proposal

Many gateways are not successfully redirecting sandbox images to https, which results in permaweb apps not consistently showing images between gateways. 

I wanted to recommend that the documentation recommends defaulting `SANDBOX_PROTOCOL="https"` to make it easier for gateway operators to fully support permaweb applications.

**Comment by djwhitt** [comment]
@twilson63 Thanks for the suggestion! Seems reasonable given that we plan to make `https` a requirement for network participation.

**Comment by djwhitt** [comment]
Updated the default to `https` on dev. That'll get merged into `main` in the next week or two as we push out network related updates. I expect most gateways will update then.
