### ISSUE TITLE
feat(envoy): IPv6 Support

### ISSUE THREAD

**Issue by kay-is** [ar-io/ar-io-node#76]
I'm building the Envoy image since I changed the config template for IPv6 support.

I needed these changes to make things work on Fly.io, which doesn't support Docker Compose.

https://github.com/kay-is/ar-io-node/blame/fly-deployment/envoy/envoy.template.yaml#L5

Are you interested in merging them? They should be backward compatible with IPv4.

That would save me some reconciliation work in the future.

**Comment by kay-is** [comment]
cc @djwhitt 👀

**Comment by djwhitt** [comment]
@kay-is Hey, sorry for missing this initially. Yeah, IPv6 compatibility changes are very welcome.

**Comment by kay-is** [comment]
@djwhitt No worries. I added a PR.

**Comment by djwhitt** [comment]
PR merged. Thanks!
