### ISSUE TITLE
TypeError due to subdomain logic

### ISSUE THREAD

**Issue by handlebauer** [ar-io/ar-io-node#88]
When I specify an `ARNS_ROOT_HOST` that includes a subdomain and then try to query that node from localhost, I receive:

```bash
$ curl localhost:4000/ar-io/healthcheck
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Internal Server Error</pre>
</body>
</html>
```

I notice in [`middleware/arns.ts`](https://github.com/ar-io/ar-io-node/blob/924a88542c74c8df7177e362b2ed0e0127755ca6/src/middleware/arns.ts) that if `ROOT_HOST_SUBDOMAIN_LENGTH` is greater than `req.subdomains.length` (true when requesting from localhost), it is possible for `arnsSubdomain` to evaluate to `undefined`.

If `arnsSubdomain` is `undefined`, then
https://github.com/ar-io/ar-io-node/blob/924a88542c74c8df7177e362b2ed0e0127755ca6/src/middleware/arns.ts#L50
results in `TypeError: Cannot read properties of undefined (reading 'length')`.

Potential fix: return early if `req.subdomains.length` is also less than `ROOT_HOST_SUBDOMAIN_LENGTH`

**Comment by djwhitt** [comment]
Thanks for the very well written issue! We'll fix this up in the next release.
